[package]
name = "audio-from-video"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = true
