name: release windows x86_64

on:
  workflow_dispatch:

jobs:
  build:
    name: release windows x86_64

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Archive audio-from-video
        run: Compress-Archive -Path target/release/audio-from-video.exe -DestinationPath C:\Users\runneradmin\audio-from-video_x86_64_msvc_windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: audio-from-video_x86_64_msvc_windows.zip
          path: C:\Users\runneradmin\audio-from-video_x86_64_msvc_windows.zip
        